### ISSUE TITLE
Add support for switching in mozaik v2?

### ISSUE THREAD

**Issue by knackjax** [juhamust/mozaik-ext-switch#1]
How hard would it be to add switching capability to mozaik v2? 

I noticed that div class are random strings now so I am not sure how you can take advantage of class names in v2

Thanks,

**Comment by juhamust** [comment]
Idea of the widget is simple, so adding the support should not be hard. Will have to check.

**Comment by knackjax** [comment]
thanks, I was having trouble since v2 is using css-in-js instead of styl in v1

**Comment by knackjax** [comment]
any luck on this? if not, do you have any guidelines how to proceed, I could take a shot... thanks

**Comment by juhamust** [comment]
@knackjax Sorry for the delay. I finally found some time to start with the porting: https://github.com/plouc/mozaik/issues/134

**Comment by knackjax** [comment]
@juhamust no problem, I just used timers that switched out divs within a widget. It is not elegant as your switch solution but this is lower priority for me now if you have other work. Thanks

**Comment by juhamust** [comment]
It took a time, but now there should be an initial working version available: https://github.com/juhamust/mozaik-ext-switch/tree/mozaik-2

There is no npm release available yet.

Please let me know if there are any issues.

**Comment by knackjax** [comment]
Thanks @juhamust. We are working other projects at the moment but when we have the chance, I hope to circle back around to this.
