### ISSUE TITLE
For which version of Mozaik this extension works

### ISSUE THREAD

**Issue by brenopolanski** [juhamust/mozaik-ext-switch#3]
For which version of Mozaik this extension works?

Mozaik  v1 or Mozaik v2?

**Comment by brenopolanski** [comment]
I'm testing on Mozaik v1 and i have the error below:

![screenshot from 2018-08-03 21-45-23](https://user-images.githubusercontent.com/1894191/43670799-a320de20-9766-11e8-8646-71279a96180a.png)

**Comment by juhamust** [comment]
The `master` branch works with Mozaik 1 but `mozaik-2` should work with Mozaik 2. Please try it out: https://github.com/juhamust/mozaik-ext-switch/tree/mozaik-2
